- name: setup workers
  hosts: gcp_function_worker
  remote_user: tgretler
  vars:
    service_account_file: ./terraform-test-key.json
    project: terraform-test-270912
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:

    - name: download docker script
      get_url:
        url: https://get.docker.com
        dest: ~/get-docker.sh 
        mode: '0777'

    - name: Execute docker installl script
      command: sh ~/get-docker.sh 
      become: yes

    - name: isntall ifconifg
      apt:
        name: "{{ item }}"
        update_cache: yes
        force_apt_get: yes
      with_items:
        - iptables
        - arptables
        - ebtables
      become: yes



    - name: install k8s dependecies
      apt:
        name: apt-transport-https
        update_cache: yes
        force_apt_get: yes
      become: yes

    - name: download k8s stuff
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: ~/apt-key.gpg
        mode: '0777'

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: yes

    - name: Execute docker installl script
      shell: cat << EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list deb https://apt.kubernetes.io/ kubernetes-xenial main EOF
      become: yes

    - name: isntall ifconifg
      apt:
        name: "{{ item }}"
        update_cache: yes
        force_apt_get: yes
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      become: yes


    - name: install kubernetes
      command: chdir=~/ {{ item }}
      with_items:
      - sudo apt-mark hold kubelet kubeadm kubectl
      become: sudo



- name: setup master
  hosts: gcp_function_master
  remote_user: tgretler
  vars:
    service_account_file: ./terraform-test-key.json
    project: terraform-test-270912
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute
  tasks:

    - name: Update repositories cache 
      apt:
        update_cache: yes
      become: yes
    - name: setup docker requirements
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
      become: yes

    - name: setup docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable
        state: present
      become: yes


    - name: isntall docker
      apt:
        name: "{{ item }}"
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - iptables
        - arptables
        - ebtables
      become: yes

    - name: check ip table conifg
      command: chdir=~/ {{ item }}
      with_items:
      - sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
      - sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      - sudo update-alternatives --set arptables /usr/sbin/arptables-legacy
      - sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      become: yes

    - name: install k8s
      apt:
        name: "{{ item }}"
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      become: yes

    - name: install kubernetes
      command: chdir=~/ {{ item }}
      with_items:
      - sudo apt-mark hold kubelet kubeadm kubectl
      become: sudo








